baseURL = "https://kuyhxl.github.io/blog/"
theme = "blowfish"
paginate = 10
enableEmoji = true

defaultContentLanguage = "ko-kr"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[languages]
  [languages.ko-kr]
    languageName = "Korean"
    languageCode = "ko-kr"
    weight = 1
    [languages.ko-kr.params]
      title = "Kuyhxl Dev Blog"
