languageCode = "ko"
languageName = "Korean"
weight = 1
title = "Kuyhxl Dev Blog"

[params]
  displayName = "Korean"
  isoCode = "ko"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/blowfish_logo_transparent.png"
  description = "Whatever"

[params.author]
  name = "Mark Hwang"
  email = "markhwang710@gmail.com"
  image = "img/blowfish_logo.png"
  headline = "Whatever"
  bio = "Whatever"
  links = [
    { Instagram = "https://www.instagram.com/kuyhxl/" },
    { github = "https://github.com/kuyhxl" },
  ]